name: Deploy JSON
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3.6.0
              with:
                node-version: '19.6.1'

            - name: Install tutors-html
              run: |
                  npm install --global tutors-json@2.6.5
            
            - name: Build site
              run: |
                  tutors-json
            
            - name: Deploy GitHub Pages
              run: |
                  git worktree add gh-pages
                  git config user.name "Deploy from CI"
                  git config user.email ""
                  cd gh-pages
                  # Delete the ref to avoid keeping history.
                  git update-ref -d refs/heads/gh-pages
                  rm -rf *
                  mv ../json/* .
                  git add .
                  git commit -m "Deploy $GITHUB_SHA to gh-pages"
                  git push --force --set-upstream origin gh-pages
